### ISSUE TITLE
Broken: 'SDClipModel' object has no attribute 'empty_tokens'

### ISSUE THREAD

**Issue by dathide** [laksjdjf/cd-tuner_negpip-ComfyUI#4]
This error prevents me from using negpip at all. Here is the basic workflow I get the error with:
![basic-workflow](https://github.com/laksjdjf/cd-tuner_negpip-ComfyUI/assets/47128084/a7217b83-7191-438f-b41d-41748314f99d)
Here is the error:
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/sapien/m2/ai-img/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/nodes.py", line 56, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/comfy/sd.py", line 130, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/comfy/sd1_clip.py", line 535, in encode_token_weights
    out, pooled = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/custom_nodes/cd-tuner_negpip-ComfyUI/negpip.py", line 43, in encode_token_weights
    to_encode = list(self.empty_tokens)
                     ^^^^^^^^^^^^^^^^^
  File "/home/sapien/m2/ai-img/ComfyUI/venv-py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SDClipModel' object has no attribute 'empty_tokens'
```
Edit: My python 3.10 packages are fully up to date with PyTorch 2.1.1 and CUDA 12.1 on an NVIDIA GPU.
Edit2: The same error occurs with Python 3.10 and CUDA 11.8 packages.
Edit3: The same error occurs with Python 3.11 and CUDA 12.1 packages.

**Comment by laksjdjf** [comment]
i updated it.
